<script setup lang="ts">
import {
  LayoutDashboard,
  ArrowLeftRight,
  Shapes,
  Wallet,
  ChartNoAxesCombined,
  UserRound,
  LogOut,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  Search,
  ChevronLeft,
  ChevronRight,
  X,
  Menu,
  TrendingUp,
  TrendingDown,
  Receipt,
  Pencil,
  Trash2,
  Download,
  ChevronDown,
  Leaf,
  Circle,
  Utensils,
  ShoppingBag,
  Car,
  House,
  Film,
  Heart,
  BriefcaseBusiness,
  Laptop,
  ShieldCheck,
  ArrowRight,
  Check,
  AlertCircle,
  LoaderCircle,
} from 'lucide-vue-next'
const props = defineProps<{ name: string; size?: number }>()
const icons = {
  dashboard: LayoutDashboard,
  transactions: ArrowLeftRight,
  categories: Shapes,
  budgets: Wallet,
  reports: ChartNoAxesCombined,
  profile: UserRound,
  logout: LogOut,
  plus: Plus,
  up: ArrowUpRight,
  down: ArrowDownLeft,
  search: Search,
  left: ChevronLeft,
  right: ChevronRight,
  close: X,
  menu: Menu,
  trend: TrendingUp,
  decline: TrendingDown,
  receipt: Receipt,
  edit: Pencil,
  delete: Trash2,
  download: Download,
  chevron: ChevronDown,
  leaf: Leaf,
  circle: Circle,
  utensils: Utensils,
  bag: ShoppingBag,
  car: Car,
  home: House,
  film: Film,
  heart: Heart,
  briefcase: BriefcaseBusiness,
  laptop: Laptop,
  shield: ShieldCheck,
  arrow: ArrowRight,
  check: Check,
  alert: AlertCircle,
  loading: LoaderCircle,
}
const icon = computed(() => icons[props.name as keyof typeof icons] ?? Circle)
</script>
<template>
  <component
    :is="icon"
    :size="size || 20"
    :stroke-width="1.8"
    aria-hidden="true"
  />
</template>
