import { z } from 'zod'

export const currencyCodes = [
  'USD',
  'EUR',
  'GBP',
  'CNY',
  'JPY',
  'CAD',
  'AUD',
  'NZD',
  'CHF',
  'SGD',
  'HKD',
  'TWD',
  'KRW',
  'INR',
  'PHP',
  'IDR',
  'MYR',
  'THB',
  'VND',
  'PKR',
  'BDT',
  'LKR',
  'SEK',
  'NOK',
  'DKK',
  'PLN',
  'CZK',
  'HUF',
  'RON',
  'TRY',
  'BRL',
  'MXN',
  'ZAR',
  'AED',
  'SAR',
  'QAR',
  'KWD',
  'BHD',
  'ILS',
  'EGP',
  'NGN',
  'KES',
] as const

export type CurrencyCode = (typeof currencyCodes)[number]
export const currencySchema = z.enum(currencyCodes)

const names: Record<CurrencyCode, string> = {
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  CNY: 'Chinese Yuan',
  JPY: 'Japanese Yen',
  CAD: 'Canadian Dollar',
  AUD: 'Australian Dollar',
  NZD: 'New Zealand Dollar',
  CHF: 'Swiss Franc',
  SGD: 'Singapore Dollar',
  HKD: 'Hong Kong Dollar',
  TWD: 'New Taiwan Dollar',
  KRW: 'South Korean Won',
  INR: 'Indian Rupee',
  PHP: 'Philippine Peso',
  IDR: 'Indonesian Rupiah',
  MYR: 'Malaysian Ringgit',
  THB: 'Thai Baht',
  VND: 'Vietnamese Dong',
  PKR: 'Pakistani Rupee',
  BDT: 'Bangladeshi Taka',
  LKR: 'Sri Lankan Rupee',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  PLN: 'Polish Zloty',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RON: 'Romanian Leu',
  TRY: 'Turkish Lira',
  BRL: 'Brazilian Real',
  MXN: 'Mexican Peso',
  ZAR: 'South African Rand',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  QAR: 'Qatari Riyal',
  KWD: 'Kuwaiti Dinar',
  BHD: 'Bahraini Dinar',
  ILS: 'Israeli New Shekel',
  EGP: 'Egyptian Pound',
  NGN: 'Nigerian Naira',
  KES: 'Kenyan Shilling',
}

export const currencyOptions = currencyCodes.map((code) => ({
  code,
  name: names[code],
}))
